import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "./ui/headernav";
import Footer from "./ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-nextposter bg-black1`}>
      <div className="w-full px-8 sticky top-0 z-50 bg-black2 smallPhone:px-4">
        <div className="desktop:w-[calc(1600px-258px)] laptop:w-full m-auto ">
          <HeaderNav/>
        </div>
      </div>
      {children}
      <div className="w-full bg-[black]  sm:m-8">
        <footer className="">
          <div className="bg-[black] desktop:w-[calc(1600px-258px)] laptop:w-full m-auto ">
            <Footer />
          </div>
        </footer>
      </div>
      </body>
    </html>
  );
}
