import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "./ui/headernav";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-nextposter px-[185px] text-white bg-black1`}>
        <HeaderNav/>
        <main className="w-[calc(1600px-128px)] px-[64px] ">
        {children}
        </main>
        <footer></footer>
      </body>
    </html>
  );
}
