import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import HeaderNav from "./ui/headernav";
import Footer from "./ui/footer";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`font-nextposter px-[185px] text-white bg-black1 select-none *:w-[calc(1600px-128px)] *:px-[64px]`}>
        <HeaderNav/>
        <main>
        {children}
        </main>
        <footer>
          <Footer/>
        </footer>
      </body>
    </html>
  );
}
